// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pquduubqdwotjevyhnxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxdWR1dWJxZHdvdGpldnlobnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjA0MTksImV4cCI6MjA2ODgzNjQxOX0.YPrN-i_0vZvncNxsYOxJ4p6s-MUdlTP_c97ejLNKn4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});